title: Shantanu Solanki # your name (or website title) here
logo: "/images/ArboretumPic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h1>MS in Statistics<h1> 
  <h2>Data Scientist<h2> 
  <br><br>
  <a href="https://www.linkedin.com/in/shantanu-solanki-014282202/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://github.com/shantanu6378">View My GitHub Profile</a>
theme: jekyll-theme-minimal
